### ISSUE TITLE
issues の作成

### ISSUE THREAD

**Issue by makki0205** [HAL-ETrob-Developer/2016-ETrob#2]
夏休みまでにやるべきことのissuesを作成する
できるだけ噛み砕いて書く
- 目標 : 30程度

**Comment by makki0205** [comment]
一年生でできるだけのコーディングをやってもらうために個々を簡単な関数にすると良い

**Comment by N-Ohtsuka** [comment]
今回1年生は仕事割り振らないので、それベースで作成しますね。

**Comment by N-Ohtsuka** [comment]
こんな雰囲気ですか？ @makki0205

**Comment by makki0205** [comment]
なるほど！
コーディングはだれがしますか？
@N-Ohtsuka

**Comment by N-Ohtsuka** [comment]
上野さんは絶対として、あとは有志をつのる形ですね。
一応僕は今回コーディングしないことになっていますが、そうは行かない気配を感じています・・・
@makki0205

**Comment by makki0205** [comment]
これからも逐一作成してください
