### ISSUE TITLE
UML修正版アップロード依頼

### ISSUE THREAD

**Issue by show-t** [HAL-ETrob-Developer/2016-ETrob#20]
先日レビューを行ったUML(クラス図)の修正版をアップロードお願いします。
コーディングのクラス名選定(スケルトン作成)に必要になると考えられます。

**Comment by N-Ohtsuka** [comment]
ssh通信がうまくいかなくてリポジトリをクローンできないので最悪今日帰ってからのアップロードになります
個人にLINEで送るのだったら今でもできると思います。
@show-t

**Comment by show-t** [comment]
今すぐじゃなくて大丈夫です。後ほどアップロードしておいてください。
@N-Ohtsuka

**Comment by N-Ohtsuka** [comment]
じゃあクローンできた段階で出します
@show-t

**Comment by N-Ohtsuka** [comment]
やっぱり家だったらクローンできましたね・・・
とりあえずプッシュしたので、確認お願いします。
@show-t

**Comment by show-t** [comment]
確認しました。ありがとうございます。
@N-Ohtsuka
