### ISSUE TITLE
Issuesにリンク！！

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#21]
イッシュにリンクを付ける実験

**Comment by N-Ohtsuka** [comment]
一応上にリンクっぽいのできましたが、こんなんでどうでしょう？
@N-OhtsukaN-Ohtsuka pushed a commit that referenced this issue 11 minutes ago
    各調整 イッシュリンク実験#21

**Comment by N-Ohtsuka** [comment]
それともこんな感じですか？
[Source](https://github.com/HAL-ETrob-Developer/2016-ETrob/tree/master/Source)

**Comment by makki0205** [comment]
下の方ですね
[webラジコンりーどみー](https://github.com/HALDevelopersTeam/HEW-raspberryPI/blob/master/README.md)
こんな感じでファイル直で指定するとわかりやすいです

こんな感じでそのissuesで関連のあるファイルのリンクを貼り付けていただいて、
任された人が作業開始できるような状態が整えばassignしてください！

**Comment by N-Ohtsuka** [comment]
了解です
じゃあスケルトン終わり次第、各イッシュにリンクに貼ってアサイン入れるみたいな感じでいきます

**Comment by makki0205** [comment]
あとリファレンスとアクティビティー図も貼っていただけるとありがたいです。

ではこちらのissueは閉じさせていただきますね

**Comment by makki0205** [comment]
すみませんやっぱり
リンク貼り終わるまで空けときますので
貼れ次第閉じてください！

**Comment by N-Ohtsuka** [comment]
リファレンスは貼りおわってますよ
[ev3rt-beta6-2-Reference](https://github.com/HAL-ETrob-Developer/2016-ETrob/tree/master/Source/ev3rt-beta6-2-Reference)
イッシュ開いてすぐ閉じちゃったので分かり辛かったですね
つぎはもうちょっと工夫しますね

**Comment by makki0205** [comment]
とりあえず閉じます
