### ISSUE TITLE
ev3apiリファレンスアップロード

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#22]

**Comment by N-Ohtsuka** [comment]
リファレンスアップロードしましたので確認よろしくお願いします
[ev3rt-beta6-2-Reference](https://github.com/HAL-ETrob-Developer/2016-ETrob/tree/master/Source/ev3rt-beta6-2-Reference)
確認終了次第アサイン外してどうぞ

**Comment by makki0205** [comment]
OKです

**Comment by N-Ohtsuka** [comment]
リファレンス見たらアサイン下げてねー
@yam123 
@ToruUeno 
@ko-da 
@kawaikazuma

**Comment by yam123** [comment]
確認しました

**Comment by kawaikazuma** [comment]
確認しました
