### ISSUE TITLE
【UML】機能-ハードウエア制御[ジャイロ]

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#23]

**Comment by N-Ohtsuka** [comment]
アクティビティ図完成です
[【UML】ジャイロセンサ管理者](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/UML/【UML】ET2016_rev0.4.0.png/ET2016_rev0.4.0/モデル/ジャイロセンサ管理者.png)
確認お願いします。_(:3｣ ∠)_

**Comment by show-t** [comment]
確認しました(*‘ω‘ *)
