### ISSUE TITLE
【UML】機能-ハードウエア制御[光学

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#24]

**Comment by N-Ohtsuka** [comment]
アクティビティ図できましたー
[【UML】光学センサ管理者](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/UML/【UML】ET2016_rev0.4.0.png/ET2016_rev0.4.0/モデル/光学センサ管理者.png)
ご確認くださいm(_ _)m

**Comment by show-t** [comment]
確認しました(*‘ω‘ *)
