### ISSUE TITLE
【UML】機能-ハードウエア制御[モータ左右]

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#25]

**Comment by N-Ohtsuka** [comment]
アクティビティ図が完成しましたよ
[【UML】走行管理者](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/UML/【UML】ET2016_rev0.4.0.png/ET2016_rev0.4.0/モデル/走行管理者.png)
確認よろしくです！

**Comment by makki0205** [comment]
OKdesu
