### ISSUE TITLE
【UML】機能-ハードウエア制御[尻尾]

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#26]

**Comment by N-Ohtsuka** [comment]
アクティビティ図完成ほやほやです
[【UML】尻尾管理者](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/UML/【UML】ET2016_rev0.4.0.png/ET2016_rev0.4.0/モデル/尻尾管理者.png)
確認ください。( ｀ー´)ノ

**Comment by kawaikazuma** [comment]
アクティビティ図を確認致しました

**Comment by yam123** [comment]
確認しました
