### ISSUE TITLE
UMLの画像化

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#27]
現状のUML資料を画像化しましたので、対応ソフト無くて見れなかった人はこっちで確認してみてください
[【UML】ET2016_rev0.3.1.png](https://github.com/HAL-ETrob-Developer/2016-ETrob/tree/master/UML/【UML】ET2016_rev0.3.1.png)
確認終わったらアサインを外してくださいね

**Comment by makki0205** [comment]
OKです！
