### ISSUE TITLE
【コーディング】機能-ハードウエア制御[光学]

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#5]

**Comment by N-Ohtsuka** [comment]
おまたせしましたスケルトンできました
[deviceope](https://github.com/HAL-ETrob-Developer/2016-ETrob/tree/master/Source/EV3_HAL2016_Ver0711/deviceope)
↑のフォルダ内の「RayReflectAdmin_ohs.cpp」「RayReflectAdmin_ohs.h」が担当になります
どうぞよろしくお願いします。

**Comment by show-t** [comment]
スケルトン作ってたんですねｗ
一から自分で作ってました(・ω<)
早めに気づいて良かった…(^_^;)

**Comment by N-Ohtsuka** [comment]
アクティビティ図にあるタイマ割り込みは
[`app.cpp`](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/Source/EV3_HAL2016/app.cpp)
により呼ばれます。

これは引数・戻り値無しに呼ばれますので、コーディングの実装としては
このとき呼ばれるメソッドの実装をして頂いて、コード内にタイマ割り込みの
仕組みは書かなくて大丈夫です。

**Comment by N-Ohtsuka** [comment]
ビルド通ったので、あとはデバイスに組み込んで動作チェックして完了です。
[コードチェック・ビルド通過](https://github.com/HAL-ETrob-Developer/2016-ETrob/commit/b2837eed4944c438fa93312d1470f85d8c459885)
@show-t
