### ISSUE TITLE
【コーディング】機能-ハードウエア制御[モータ左右]

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#7]

**Comment by N-Ohtsuka** [comment]
スケルトン完成の巻！
[deviceope](https://github.com/HAL-ETrob-Developer/2016-ETrob/tree/master/Source/EV3_HAL2016/deviceope)
↑の「RunningAdmin_ohs.cpp」「RunningAdmin_ohs.h」です。
確認よろしくです！

**Comment by makki0205** [comment]
初めてのC＋＋頑張ります

**Comment by makki0205** [comment]
[アクティビティー図](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/UML/%E3%80%90UML%E3%80%91ET2016_rev0.4.0.png/ET2016_rev0.4.0/%E3%83%A2%E3%83%87%E3%83%AB/%E8%B5%B0%E8%A1%8C%E7%AE%A1%E7%90%86%E8%80%85.png)

**Comment by makki0205** [comment]
タイマー割り込み仕組みはわかりますが、
書き方わかんないっす！！
@N-Ohtsuka

**Comment by N-Ohtsuka** [comment]
アクティビティ図にあるタイマ割り込みは
[`app.cpp`](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/Source/EV3_HAL2016/app.cpp)
により呼ばれます。

これは引数・戻り値無しに呼ばれますので、コーディングの実装としては
このとき呼ばれるメソッドの実装をして頂いて、コード内にタイマ割り込みの
仕組みは書かなくて大丈夫です。

**Comment by makki0205** [comment]
進捗　C++の仕様とAPIの仕様がよく分からないので明日ミーティング参加します。
APIが支えてる前提での取得系コーディング終了
レビューお願いします
@N-Ohtsuka

**Comment by N-Ohtsuka** [comment]
了解です。
明日レビューまでににプッシュされたコード確認しておくので、それまでお休みください。
とりあえずはお疲れ様です。

**Comment by N-Ohtsuka** [comment]
[バランサー](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/Source/EV3_HAL2016/calculation/Balancer_ohs.cpp)の存在をすっかり忘れてました！
これにより走行管理者のメソッドが増えてしまったので、追加お願いします。
- [走行管理者.png](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/UML/【UML】ET2016_rev0.4.2.png/ET2016_rev0.4.2/モデル/走行管理者.png)
- [全体クラス.png](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/UML/【UML】ET2016_rev0.4.2.png/ET2016_rev0.4.2/モデル/全体クラス.png)

内容はメンバの値をそのまま吐き出すだけのメソッドなので苦ではないと思いますすいません。
