### ISSUE TITLE
【コーディング】機能-ハードウエア制御[尻尾]

### ISSUE THREAD

**Issue by N-Ohtsuka** [HAL-ETrob-Developer/2016-ETrob#8]

**Comment by N-Ohtsuka** [comment]
スケルトン完成です！
[deviceope](https://github.com/HAL-ETrob-Developer/2016-ETrob/tree/master/Source/EV3_HAL2016_Ver0711/deviceope)の中の
「TailAdmin_ohs.cpp」「TailAdmin_ohs.h」のコーディングをお願いします。

**Comment by yam123** [comment]
サンプル見ながら解読しています。

**Comment by N-Ohtsuka** [comment]
アクティビティ図にあるタイマ割り込みは
[`app.cpp`](https://github.com/HAL-ETrob-Developer/2016-ETrob/blob/master/Source/EV3_HAL2016/app.cpp)
により呼ばれます。

これは引数・戻り値無しに呼ばれますので、コーディングの実装としては
このとき呼ばれるメソッドの実装をして頂いて、コード内にタイマ割り込みの
仕組みは書かなくて大丈夫です。

**Comment by N-Ohtsuka** [comment]
単体テスト用のプログラム作ったので明日デバイスに入れて動作確認取ってみます。
それが成功し次第このイッシュをクローズします。
@yam123
